"""Static mock listings used as the candidate pool for the AI Need Board."""

MOCK_LISTINGS = [
    {
        "id": "1",
        "title": "Dell Inspiron 15 Laptop",
        "description": "Dell Inspiron 15 with Intel i5 10th gen, 8GB RAM, 512GB SSD. Great for coding and DBMS coursework. Minor scratches on lid.",
        "price": 28000,
        "condition": "Good",
        "category": "Laptops",
        "semester": "Any",
    },
    {
        "id": "2",
        "title": "Data Structures & Algorithms Textbook",
        "description": "CLRS Introduction to Algorithms 3rd edition. Lightly used, no highlights. Perfect for 3rd and 4th semester CS students.",
        "price": 650,
        "condition": "Like New",
        "category": "Books",
        "semester": "3rd",
    },
    {
        "id": "3",
        "title": "Scientific Calculator Casio FX-991EX",
        "description": "Casio ClassWiz FX-991EX scientific calculator. Works perfectly, comes with original case. Ideal for engineering maths.",
        "price": 900,
        "condition": "Excellent",
        "category": "Stationery",
        "semester": "1st",
    },
    {
        "id": "4",
        "title": "HP 15 Laptop – i3 8th Gen",
        "description": "HP 15 laptop with i3 8th gen processor, 4GB RAM, 1TB HDD. Battery backup around 3 hours. Good for basic college work.",
        "price": 18000,
        "condition": "Good",
        "category": "Laptops",
        "semester": "Any",
    },
    {
        "id": "5",
        "title": "Database Management Systems Book",
        "description": "Ramakrishnan & Gehrke DBMS textbook, 3rd edition. Some pencil annotations in first two chapters, otherwise clean.",
        "price": 400,
        "condition": "Good",
        "category": "Books",
        "semester": "4th",
    },
    {
        "id": "6",
        "title": "Logitech MX Keys Keyboard",
        "description": "Logitech MX Keys wireless keyboard. Barely used for 2 months. Backlit keys, multi-device pairing. Great for long coding sessions.",
        "price": 5500,
        "condition": "Like New",
        "category": "Accessories",
        "semester": "Any",
    },
    {
        "id": "7",
        "title": "Engineering Mathematics Vol 1 & 2",
        "description": "B.S. Grewal Higher Engineering Mathematics set. Both volumes included. Useful for 1st and 2nd semester engineering students.",
        "price": 500,
        "condition": "Good",
        "category": "Books",
        "semester": "1st",
    },
    {
        "id": "8",
        "title": "Lenovo IdeaPad Slim 5 – Ryzen 5",
        "description": "Lenovo IdeaPad Slim 5 with AMD Ryzen 5 5500U, 16GB RAM, 512GB SSD. Excellent performance for ML and data science projects.",
        "price": 42000,
        "condition": "Excellent",
        "category": "Laptops",
        "semester": "Any",
    },
]
